### ISSUE TITLE
strange options "opts": ",,=,a,c,d,e,i,l,m,n,o,p,r,s,t,u,z" passed to fstab

### ISSUE THREAD

**Issue by ser** [debops/ansible-cryptsetup#11]
Instead of real options, debops-cryptsetup sends 

```
failed: [bolek] => (item={u'ciphertext_block_device': u'/dev/loop5', u'name': u'lxc'}) => {"failed": true, "invocation": {"module_args": {"dump": null, "fstab": "/etc/fstab", "fstype": "btrfs", "name": "/var/lib/lxc", "opts": ",,=,a,c,d,e,i,l,m,n,o,p,r,s,t,u,z", "passno": null, "src": "/dev/mapper/lxc", "state": "mounted"}, "module_name": "mount"}, "item": {"ciphertext_block_device": "/dev/loop5", "name": "lxc"}, "msg": "Error mounting /var/lib/lxc: mount: wrong fs type, bad option, bad superblock on /dev/mapper/lxc,\n       missing codepage or helper program, or other error\n\n       In some cases useful info is found in syslog - try\n       dmesg | tail or so.\n"}
```

How can I debug it deeper?

**Comment by drybjed** [comment]
@ser Register that task in a variable and debug it. What Ansible version do you use, what OS release on the remote host?

**Comment by ypid** [comment]
As of [v0.3.0](http://docs.debops.org/en/latest/ansible/roles/ansible-cryptsetup/docs/changelog.html#v0-3-0) `cryptsetup_mount_options` and `item.mount_options` are now lists because they are easier to handle and join together in a complicated inventory like mine. Might that be the issue here? Can you post an example inventory which reproduces this?

**Comment by ser** [comment]
Bingo! It was it. I probably read previous docs. Thanks!
